; PlatformIO Project Configuration File
; 文档参考：https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
; 基础平台配置（适配 ESP32-S3 架构）
platform = espressif32
board = esp32-s3-devkitc-1  ; ESP32S3-CAM 兼容该开发板配置，无需额外自定义board
framework = arduino

; 关键硬件配置（PSRAM + Flash）
board_build.arduino.memory_type = qio_opi  ; QIO(Flash) + OPI(PSRAM) 双模适配
board_build.flash_mode = qio               ; Flash 传输模式（QIO 速率更快）
board_build.psram_type = opi               ; ESP32S3-CAM 8MB PSRAM 为 OPI 接口
board_upload.flash_size = 16MB             ; Flash 总容量 16MB
;board_build.flash_size = 8MB
board_build.partitions = default_16MB.csv  ; 16MB 专属分区表（避免内存分配异常）
board_build.extra_flags = -DBOARD_HAS_PSRAM  ; 启用 PSRAM 核心编译宏

; 串口监控配置
monitor_speed = 9600
upload_speed = 115200
monitor_filters = default, time  ; 可选：添加时间戳过滤，便于日志分析
board_build.filesystem = littlefs

; 依赖库（摄像头核心库 + 可选工具库）
;lib_deps =
;  espressif/ESP32 Camera Library@^2.0.0  ; ESP32 官方摄像头库
;  adafruit/Adafruit NeoPixel@^1.15.2     ; 可选：若需控制板载LED，保留此依赖


board_build.psram_enable = true
board_build.f_flash = 80000000L
build_flags =
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DARDUINO_USB_MODE=0   ; 1 USB-OTG 模式; 0 串口模式
  -DARDUINO_USB_CDC_ON_BOOT=0 ; 作用：是否启用 USB 虚拟串口 (CDC) （就是你用来打印日志、上传固件的串口）

;lib_compat_mode = strict
;lib_ldf_mode = off